name: module
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  converter:
    path: ../converter
  database:
    path: ../database

  moor: ^4.5.0
  moor_generator: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.1.1