name: converter
description: A new Flutter package project.
version: 0.0.1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  moor: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter